version: "3.1"
services:

  go-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: go-api
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
