version: "3.1"
services:

  go-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: go-api
    ports:
      - "80:8080"
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - 6379

  mysql:
    image: mysql:5.7
    container_name: mysql
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=api
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql:db
    ports:
      - "8080:80"